import data from '../data/results.json';
import rawUrl from '../raw/report.txt?url';
import pdfUrl from '../../Project_Report_Parallel_SSSP.pdf?url';
import './style.css';

type Point = typeof data.points[number];
const number = (n: number): string => n.toLocaleString('en-US');
const comparison = data.points.filter(point => point.updates === 100000);
const chart = (points: Point[]): string => points.map(point => `<div class="bar-row"><div class="bar-label"><span>${point.mode}</span><strong>${point.speedup.toFixed(2)}×</strong></div><div class="bar-track"><div class="bar" style="width:${point.speedup / 20 * 100}%"></div></div><small>${point.configuration}</small></div>`).join('');

document.querySelector<HTMLDivElement>('#app')!.innerHTML = `
<header><a class="brand" href="#">Parallel SSSP<span> / Results notebook</span></a><nav aria-label="Main"><a href="#results">Results</a><a href="#method">Method</a><a href="#evidence">Evidence</a></nav></header>
<main id="main">
<section class="hero"><p class="eyebrow">Dynamic graphs · OpenMP · MPI</p><h1>When the graph changes,<br>keep the shortest path.</h1><p class="lede">One source. Thousands of destinations. Parallel SSSP explores how to update shortest paths when edges change, sharing the work across threads and machines.</p><a class="button" href="#results">Explore the recorded results</a><p class="source-note">A research notebook, built from the repository's project report.</p></section>
<section id="method" class="method"><div><p class="eyebrow">The idea in 30 seconds</p><h2>Repair what changed.<br>Share the work.</h2><p>First, Dijkstra finds the shortest route from one source to every reachable vertex. An inserted edge can open a shorter route; a deleted edge can invalidate a branch of the shortest-path tree.</p><p>Dynamic updates mark affected vertices, invalidate broken paths and relax distances until they settle. OpenMP shares work in one address space. MPI partitions the graph, exchanges distance information and checks convergence across ranks.</p><p class="muted">Diagram is conceptual. It shows work distribution, not a measured benchmark graph.</p></div>
<figure class="diagram"><svg viewBox="0 0 480 320" role="img" aria-labelledby="diagram-title diagram-desc"><title id="diagram-title">A graph update propagates across two partitions</title><desc id="diagram-desc">A source connects to two groups of graph vertices. A changed edge affects distances. Partitions share boundary information to update the paths.</desc><rect x="28" y="75" width="190" height="184" rx="16" fill="#edf4ff"/><rect x="262" y="75" width="190" height="184" rx="16" fill="#edf4ff"/><g fill="#405269" font-size="15"><text x="68" y="105">Partition 0</text><text x="302" y="105">Partition 1</text></g><g stroke="#9bacc2" stroke-width="3"><path d="M70 172L160 138L160 215L330 138L407 202L330 229L160 215M70 172L160 215M330 138L330 229" fill="none"/></g><path d="M160 138L330 138" stroke="#1766d7" stroke-width="5" stroke-dasharray="8 6"/><g fill="white" stroke="#1766d7" stroke-width="3"><circle cx="70" cy="172" r="19"/><circle cx="160" cy="138" r="13"/><circle cx="160" cy="215" r="13"/><circle cx="330" cy="138" r="13"/><circle cx="330" cy="229" r="13"/><circle cx="407" cy="202" r="13"/></g><text x="64" y="178" font-size="16" fill="#1766d7">S</text><text x="182" y="45" font-size="15" fill="#1766d7">Changed edge</text><path d="M239 54V123" stroke="#1766d7"/><text x="108" y="298" font-size="15" fill="#405269">Exchange distances · Check convergence</text></svg><figcaption>Source S → affected vertices → updated distances</figcaption></figure></section>
<section id="results"><div class="section-heading"><div><p class="eyebrow">Recorded evidence</p><h2>What the report tells us</h2></div><span class="badge">${data.dataset}</span></div><p class="section-intro">These are reported speedups over the serial implementation. No fresh benchmarks were run. Values are transcribed from prose, not estimated from chart pixels.</p><div class="results-grid"><article class="panel"><p class="eyebrow">Same reported update count</p><h3>100,000 edge updates</h3><p class="muted">Speedup over serial · higher is faster</p><div class="chart" role="img" aria-label="At 100,000 updates, MPI reports 6.45 times speedup and MPI plus OpenMP reports 18.03 times speedup.">${chart(comparison)}<div class="axis"><span>0×</span><span>10×</span><span>20×</span></div></div><p class="caption">MPI: report pp. 20, 36. Hybrid: p. 35. The report does not supply raw timings or uncertainty for these observations.</p></article><article class="panel note"><p class="eyebrow">A result to investigate</p><div class="stat">39.35<span>×</span></div><h3>Reported OpenMP speedup</h3><p>12,500 updates with 2 threads (p. 21). This is a different workload from the comparison at left.</p><p>The report itself describes this result as an anomaly. Without raw trials and correctness checks, it should not be read as a general scaling guarantee.</p></article></div>
<p class="caption">Scroll the table horizontally on smaller screens to see every column.</p><div class="table-wrap" role="region" tabindex="0" aria-label="Recorded observations, scroll horizontally for all columns"><table><caption>Every plotted and highlighted observation</caption><thead><tr><th scope="col">Mode</th><th scope="col">Updates</th><th scope="col">Configuration</th><th scope="col">Speedup</th><th scope="col">Report page</th></tr></thead><tbody>${data.points.map(p=>`<tr><th scope="row">${p.mode}</th><td>${number(p.updates)}</td><td>${p.configuration}</td><td>${p.speedup.toFixed(2)}×</td><td><a href="${pdfUrl}#page=${p.page}">${p.page}</a></td></tr>`).join('')}</tbody></table></div></section>
<section id="evidence" class="evidence"><div><p class="eyebrow">Read with context</p><h2>Evidence, not a leaderboard.</h2><p>The README describes serial and OpenMP tests on an Apple M3 Pro (11 cores, 18 GB), and distributed tests using that machine plus an AMD Ryzen 7 5800H (16 GB) over ZeroTier. These are historical report conditions; this site did not access those machines.</p><p>Speedup means serial time divided by parallel time. Runtime and efficiency charts are omitted because the checked-in text does not establish a complete, consistent measurement series. Report p. 34 discusses different rank counts, so the MPI configuration here is specifically attributed to p. 20.</p></div><aside class="panel"><h3>What is missing</h3><ul>${data.missing.map(item=>`<li>${item}</li>`).join('')}</ul><a href="${pdfUrl}">Read the original report (PDF)</a><br><a href="${rawUrl}" download="report.txt">Download extracted source text</a></aside></section>
</main><footer><span>Parallel SSSP / Results notebook</span><span>Four reported observations. No invented measurements.</span></footer>`;
